### PR TITLE
Performance Improvments and bug fixes for Screening Plan

### LINKED ISSUE #982: Bug - New Rating Guide Answers can cause errors on save
# Description
When you create a new Rating Guide Answer, if you add the answer text before selecting a skill, it will attempt to save to the server when focus is lost from the text input field. But, with skill_id null, it will cause an error on the server, and you'll see an error message:
```
Something went wrong!
Request failed with status code 400
```

- [ ] This bug requires a unit test.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Go to an Assessment Plan page.
2. Ensure there are some assessment types besides  Narrative Review.
3. Scroll down to a Rating Guide Question (add a question if none exist).
4. Click the plus to add an answer (delete existing answers if the plus doesn't appear).
5. Edit the answer, without selecting a skill. Click away so the form input loses focus.
6. You should see an error message.

# Additional Context
Its caused because the server validates answers such that both answer text, and criterion id, are required.

### PR DESCRIPTION
**Pull request by tristan-orourke**
Significantly boost performance of screening plan by adding memoization to redux selectors and by moving reliance on redux data as low as possible into the component tree, in order to reduce the number of renders that happen. Previously, typing anything into a single input would cause the whole page to re-render.
Resolves #982, #983, #985, #990

### CODE REVIEW

File: resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx [hunk 1]
```diff
@@ -102,7 +136,9 @@ const RatingGuideAnswer: React.FunctionComponent<
           onChange={(event): void =>
```
Comment (Khristophor) [inline resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx]: This is probably safe to leave for a future refactor, but we should stick to using named functions instead of anonymous ones (especially inside components that are repeated multiple times).

File: resources/assets/js/store/Assessment/assessmentSelector.ts [hunk 2]
```diff
@@ -1,151 +1,212 @@
-import isEqual from "lodash/isEqual";
+import { isEqual } from "lodash";
```
Comment (Khristophor) [inline resources/assets/js/store/Assessment/assessmentSelector.ts]: Make sure to import the functions directly from lodash:
```js
import isEqual from "lodash/isEqual";
```
that case in particular saves about 65kb.

File: resources/assets/js/store/Job/jobSelectorComplex.ts [hunk 3]
```diff
@@ -0,0 +1,209 @@
+import createCachedSelector from "re-reselect";
+import { uniq, difference, intersection } from "lodash";
```
Comment (Khristophor) [inline resources/assets/js/store/Job/jobSelectorComplex.ts]: Same thing here, you can import them all directly, although they have to be on individual lines.

File: resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx (hunk 1 above)
Comment (tristan-orourke) [reply resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx]: For performance purposes?

File: app/Services/Validation/Rules/CriterionRule.php [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+use App\Models\Criteria;
+
+/**
+ * Validates that value is a valid Criteria id
+ */
+class CriterionRule implements Rule
+{
+    public function passes($attribute, $value)
+    {
+        return Criteria::where('id', $value)->exists();
```
[the remark this answers is not in the document]
Comment (tristan-orourke) [reply app/Services/Validation/Rules/CriterionRule.php]: Oh yeah, this looks like it would be easy, actually. Don't know how it will compare performance wise, but it has to be minor.

File: resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx (hunk 1 above)
Comment (tristan-orourke) [reply resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx]: I'll keep that in mind in the future

File: app/Http/Requests/StoreRatingGuideAnswer.php [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+     * Determine if the user is authorized to make this request.
+     *
+     * @return bool
+     */
+    public function authorize()
+    {
+        // Ensure the user can make answers, and is the owner of the question it answers.
+        if ($this->user()->can('create', RatingGuideAnswer::class)) {
+            $questionId = $this->input("rating_guide_question_id");
+            if ($questionId) {
```
[the remark this answers is not in the document]
Comment (tristan-orourke) [reply app/Http/Requests/StoreRatingGuideAnswer.php]: #0e7cbf05268667a52c3da631641108504b02f6fe

File: resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx [hunk 6]
```diff
@@ -191,13 +257,29 @@ const mapDispatchToProps = (dispatch: DispatchType, ownProps): any => ({
...
 });
 // @ts-ignore
 const RatingGuideAnswerContainer: React.FunctionComponent<
   RatingGuideAnswerContainerProps
 > = connect(
   mapStateToProps,
   mapDispatchToProps,
-)(injectIntl(RatingGuideAnswer));
+  mergeProps,
+)(withPropsChecker(injectIntl(RatingGuideAnswer)));
```
[the remark this answers is not in the document]
Comment (tristan-orourke) [reply resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx]: 9452cc29999bf96805cf88b883d11299bc5e46e6

File: resources/assets/js/store/Assessment/assessmentSelector.ts (hunk 2 above)
Comment (tristan-orourke) [reply resources/assets/js/store/Assessment/assessmentSelector.ts]: 08ab54cb35be20b3de917d97c1bf859c40799db4

File: resources/assets/js/store/Job/jobSelectorComplex.ts (hunk 3 above)
Comment (tristan-orourke) [reply resources/assets/js/store/Job/jobSelectorComplex.ts]: 08ab54cb35be20b3de917d97c1bf859c40799db4

File: app/Services/Validation/Rules/CriterionRule.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (tristan-orourke) [reply app/Services/Validation/Rules/CriterionRule.php]: 24de2022ddb3ae50216e9927faedc5593fa471a8
