### PR TITLE
Bugfix - JPB single-page app navigation

### LINKED ISSUE #1332: Bug - Client-side navigate() method stores incorrect page title in history.
# Description
When navigating between steps of the Job Builder, every page is added to browser history with the same Page Title as the original page you navigated to.

# Steps to Reproduce
Steps to reproduce the behavior. Example:
1. Got to `/en/manager/jobs/builder`.
2. Complete the intro step, click Continue.
3. Complete the Details form, save and preview, click Continue.
4. Long press on the browser back button: both previous entries appear as `Job Builder: Intro`.

# Images
Place image attachments here.

- [ ] Regression test written.

### PR DESCRIPTION
**Pull request by yonikid15**
Resolves #1332 

### Notes:
- Set document title and h1 tag with router on react side.
- Moved translations to React-side.

### CODE REVIEW

File: resources/assets/js/helpers/router.ts [hunk 1]
```diff
@@ -37,17 +37,21 @@ export const useUrlHash = (): void => {
 };
 
 export const useRouter = (
-  routes: Routes<any, React.ReactElement>,
+  routes: Routes<any, any>,
```
Comment (tristan-orourke) [inline resources/assets/js/helpers/router.ts]: You can easily define the type as `{title: string; component: React.ReactElement}`

File: resources/assets/js/helpers/router.ts [hunk 2]
```diff
@@ -37,17 +37,21 @@ export const useUrlHash = (): void => {
...
   const [component, setComponent] = useState<React.ReactElement | null>(null);
 
   // Render the result of routing
   useEffect((): void => {
-    router
-      .resolve(location.pathname)
-      .then((result): void => setComponent(result));
+    router.resolve(location.pathname).then((result): void => {
+      const { defaultMessage } = result.title.props;
+      const h1 = document.getElementById("h1");
```
Comment (tristan-orourke) [inline resources/assets/js/helpers/router.ts]: It seems odd to me to use "h1" as an id. Why not just search for the first <h1> element?

Comment (Khristophor) [reply resources/assets/js/helpers/router.ts]:
```js
document.querySelector('h1');
```

Comment (yonikid15) [reply resources/assets/js/helpers/router.ts]: Lol. For some reason I thought you only had access to innerHTML with getElementById.

File: resources/assets/js/helpers/router.ts [hunk 3]
```diff
@@ -37,17 +37,21 @@ export const useUrlHash = (): void => {
...
   const router = useMemo(() => new UniversalRouter(routes), [routes]);
   const [component, setComponent] = useState<React.ReactElement | null>(null);
 
   // Render the result of routing
   useEffect((): void => {
-    router
-      .resolve(location.pathname)
-      .then((result): void => setComponent(result));
+    router.resolve(location.pathname).then((result): void => {
+      const { defaultMessage } = result.title.props;
```
Comment (tristan-orourke) [inline resources/assets/js/helpers/router.ts]: You're passing in an entire `FormattedMessage` React element in as `result.title`, but you're only using the props of that react element. You might as well just pass the props directly.

Actually, You're only grabbing defaultMessage from those props, which is always the English string (it doesn't get translated). I think you should try to translate the message before it gets here, so that title can be a simple string.

File: resources/assets/js/components/JobBuilder/JobBuilderRoot.tsx [hunk 4]
```diff
@@ -13,47 +14,110 @@ import JobSkillsPage from "../JobBuilderSkills/JobBuilderSkillsPage";
...
-      },
-      {
-        path: "/:id/builder/tasks",
-        action: ({ params }) => <JobTasksPage jobId={Number(params.id)} />,
-      },
-      {
-        path: "/:id/builder/skills",
-        action: ({ params }) => <JobSkillsPage jobId={Number(params.id)} />,
+        action: () => ({
+          title: <FormattedMessage {...titles.introTitle} />,
```
Comment (tristan-orourke) [inline resources/assets/js/components/JobBuilder/JobBuilderRoot.tsx]: `FormattedMessage` is a ReactElement that can only translate its contents if it's below [IntlProvider](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#intlprovider) in the React element tree. It won't be much help for setting document.title. Instead, you should call intl.formatMessage to convert it directly to a string. You could change `routes` from a constant to a function that accepts the intl object, which JobBuilderRoot can pass in.

**Comment by Khristophor** [comment]
> The react-intl v3 PR is about to be merged in. This will require a few changes after that.

I think we might be safe on this actually. The `FormattedMessage` component didn't change at all, and `defineMessages` is just an object.

File: resources/assets/js/components/JobBuilder/JobBuilderRoot.tsx (hunk 4 above)
Comment (Khristophor) [reply resources/assets/js/components/JobBuilder/JobBuilderRoot.tsx]: You can use the [new hook](https://github.com/formatjs/react-intl/blob/master/docs/API.md#useintl-hook) to grab the intl object now

File: app/Http/Controllers/JobBuilderController.php [hunk 5]
```diff
@@ -11,83 +11,76 @@ class JobBuilderController extends Controller
      * Show the Job Builder Intro page
      * @return \Illuminate\Http\Response
      */
-    public function intro($jobId = null)
+    public function intro()
     {
         return view(
-            'manager/job-builder-root',
-            ['title' => Lang::get('manager/job_builder.intro_title'), 'jobId' => $jobId]
```
Comment (tristan-orourke) [inline app/Http/Controllers/JobBuilderController.php]: Good point, this isn't necessary any more.

File: resources/assets/js/helpers/router.ts [hunk 6]
```diff
@@ -36,21 +38,33 @@ export const useUrlHash = (): void => {
   }, [location.hash, hashFound]);
 };
 
-export const useRouter = (
-  routes: Routes<any, React.ReactElement>,
-): React.ReactElement | null => {
+export const UseRouter: FunctionComponent<{
```
Comment (tristan-orourke) [inline resources/assets/js/helpers/router.ts]: I don't really like the change of UseRouter to a component. Or rather, if it is going to be changed to a component, it should not be named like a hook and should be moved to to the components folder. I'm curious why you made the change in the first place.

File: resources/assets/js/helpers/router.ts [hunk 7]
```diff
@@ -36,21 +38,33 @@ export const useUrlHash = (): void => {
...
+  routes: Routes<any, any>;
+  scrollToTop?: boolean;
+}> = ({ routes, scrollToTop }): React.ReactElement | null => {
+  const intl = useIntl();
   const location = useLocation();
   const router = useMemo(() => new UniversalRouter(routes), [routes]);
   const [component, setComponent] = useState<React.ReactElement | null>(null);
+  const tracker: HTMLElement | null = document.getElementById(
+    "job-builder-root",
+  );
```
Comment (tristan-orourke) [inline resources/assets/js/helpers/router.ts]: This is specific to the Job Builder, and breaks this hook/component's potential reusability.

File: resources/assets/js/helpers/router.ts (hunk 6 above)
Comment (yonikid15) [reply resources/assets/js/helpers/router.ts]: I remember running into multiple problems with the routes array and adding the intl hook (which needs a FC, and has to have the IntlProvider component as an ancestor) to properly translate the titles. However, I refactored everything which should resolve everything without having to make UseRouter a FC.

File: app/Http/Controllers/JobBuilderController.php [hunk 8]
```diff
@@ -11,83 +11,76 @@ class JobBuilderController extends Controller
      * Show the Job Builder Intro page
      * @return \Illuminate\Http\Response
      */
-    public function intro($jobId = null)
+    public function intro()
```
[the remark this answers is not in the document]
Comment (tristan-orourke) [reply app/Http/Controllers/JobBuilderController.php]: Yes, we can get rid of them. At this point, we can even get rid of the controller, and just return the view straight from routes. https://laravel.com/docs/6.x/routing#view-routes

File: resources/assets/js/helpers/router.ts (hunk 6 above)
Comment (tristan-orourke) [reply resources/assets/js/helpers/router.ts]: Nicely done.
